FROM python:3.14-slim
WORKDIR /app
COPY requirements.seeder.txt ./requirements.txt
RUN pip install -r requirements.txt --no-cache-dir
COPY fetch_and_seed_courses.py ./
CMD ["python", "fetch_and_seed_courses.py"]
