apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: team-devvopps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-service
  template:
    metadata:
      labels:
        app: llm-service
    spec:
      containers:
        - name: llm-service
          image: ghcr.io/aet-devops26/team-devvopps/llm-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: COURSE_SERVICE_HOST
              value: course-service
            - name: LLM_API_URL
              value: http://llm-backend:1234/v1/chat/completions
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10