apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: team-devvopps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
        monitoring: "true"
    spec:
      containers:
        - name: course-service
          image: team-devvopps/course-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: coursedb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
