apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadmap-service
  namespace: team-devvopps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadmap-service
  template:
    metadata:
      labels:
        app: roadmap-service
        monitoring: "true"
    spec:
      containers:
        - name: roadmap-service
          image: team-devvopps/roadmap-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: roadmapdb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: USER_SERVICE_HOST
              value: user-service
            - name: LLM_SERVICE_HOST
              value: llm-service
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
