apiVersion: v1
kind: Service
metadata:
  name: roadmap-service
  namespace: team-devvopps
spec:
  type: ClusterIP
  selector:
    app: roadmap-service
  ports:
    - port: 8083
      targetPort: 8083
