apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pvc
  namespace: {{ .Values.namespace }}
spec:
  # ReadWriteOnce = only one pod can mount this volume (Grafana pod is single replica)
  # Use ReadWriteMany if you scale to multiple Grafana pods for HA
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
