apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'team-devvopps'

    rule_files:
      - '/etc/prometheus/alerts/alerts.yaml'

    scrape_configs:
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:{{ .Values.services.userService.port }}']
        metrics_path: '/actuator/prometheus'

      - job_name: 'course-service'
        static_configs:
          - targets: ['course-service:{{ .Values.services.courseService.port }}']
        metrics_path: '/actuator/prometheus'

      - job_name: 'roadmap-service'
        static_configs:
          - targets: ['roadmap-service:{{ .Values.services.roadmapService.port }}']
        metrics_path: '/actuator/prometheus'

      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:{{ .Values.services.apiGateway.port }}']
        metrics_path: '/actuator/prometheus'
