apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: team-devvopps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: team-devvopps/client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
