apiVersion: v1
kind: Secret
metadata:
  name: llm-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  groq-api-key: {{ .Values.llmService.groqApiKey | default "" }}
  logos-api-key: {{ .Values.llmService.logosApiKey | default "" }}
