apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: llm-service
  ports:
    - port: {{ .Values.services.llmService.port }}
      targetPort: {{ .Values.services.llmService.port }}
