apiVersion: v1
kind: Service
metadata:
  name: roadmap-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: roadmap-service
  ports:
    - port: {{ .Values.services.roadmapService.port }}
      targetPort: {{ .Values.services.roadmapService.port }}
