openapi: 3.0.3

info:
  title: User Service API
  description: Manages user accounts
  version: 1.0.0


servers:
  - url: /api/v1
    description: Via API Gateway


tags:
  - name: users
    description: User account management


paths:

  /users:
    get:
      tags: [users]
      summary: Get all users
      operationId: getAllUsers

      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags: [users]
      summary: Create a new user
      operationId: createUser

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


  /users/{id}:
    get:
      tags: [users]
      summary: Get a user by ID
      operationId: getUser

      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Matching user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags: [users]
      summary: Delete a user by ID
      operationId: deleteUser

      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User deleted successfully

        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    UserRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: User's name

    User:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        name:
          type: string

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string