name: Lint Code

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  lint-client:
    name: Lint React Client (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install
        working-directory: client

      - name: Run ESLint
        run: npm run lint
        working-directory: client

  lint-java:
    name: Lint Java Services (SpotBugs)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Run SpotBugs
        run: ./gradlew check -x test --scan
        working-directory: server

  lint-actions:
    name: Lint GitHub Actions Workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: devops-actions/actionlint@v0.1.12

  lint-helm:
    name: Lint Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: |
          helm lint "helm/team-devvopps/" \
            --set "postgres.credentials.username=testuser" \
            --set "postgres.credentials.password=testpass123"
  
  lint-openapi:
    name: Lint OpenAPI Specs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint OpenAPI files
        run: |
          for file in api/*.yaml
          do
            echo "Linting $file"
            redocly lint "$file"
          done
