name: Lint Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint-client:
    name: Lint React Client (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install
        working-directory: client

      - name: Run ESLint
        run: npm run lint
        working-directory: client

  lint-java:
    name: Lint Java Services (SpotBugs)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Run SpotBugs
        run: ./gradlew check -x test --scan
        working-directory: server

  lint-actions:
    name: Lint GitHub Actions Workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: rhysd/actionlint-action@v1
